language: ruby
rvm:
- 2.2
branches:
  only:
  - master
script:
- bundle exec jekyll build
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GH_REF}" HEAD:${TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/themodelvillager/bekonscot.git
  - TARGET_BRANCH: gh-pages
  - secure: CWqABJH8HUv0XlyFEuAgVMahbK3j+wAjMhzmNZvxLC3cPqhpXn1GRWuRCHgKqPwifTjg+j9Pi3HT8xShwumI5XdhSfG3RjLE2hfdQVct3cvYyVI3x2Su9BlwYsmTPMBO4ei5FVpiqZCuOXHn2z/5RS/8hAzqM07SznFIHsYO/F832lCsDBnitWr0+DPXQc7aIkGMz5RQrTqdOiC/Tdcc0lrCxG3z0WHKfaj4FGupFJf5XjlJ7w4iNoyd2/QX3VbooYXHKPXCUG0byODwPghsgfgyviDQ+nHoD01eXBp95r0hjq9inX26aQGpLWBe75/WX+awnNpNkAimXluormY2l0OExY90uCpRy7IbdYtMBAcuZq+VksqDWg9AD0OweU/0lQxEYXhNhRPPt3SCvgYxFYsd2ozKPfbWuTjrEayTr4tOsVDpkPgY8ZllbOn5B91l3DnwTI7uC/hhJ8/61enuEeLd3CqD9ntdcizFERkFgHoBHsxSpd70ZFrZO6RNx/Xxhj+q/DDFzdc2UPhGhPKrFaEXeMvkCG7VahPx4Fy4bPt15urYnzP7pbTdz9/5jCQVQvbZ4ACUbyNqUTR3L7ht6jobRFrYXS7jYe47Ep7IwXfUEPitYpR3AqbHAb6K2hjlZZNgujHQAL36nwvUwIaFstBoWSo9lOOdgAbatrtIoXE=
  - secure: Ye6sndMDfx/s1xRN33zP4Kezauqm6gDWoTAMX8TwvPR4a+LyyR5rh7L/BEWWtzqBRSnUjHN9IJfbz9Jp048/LFmy3BIawMQDFqjXmSqXnrjLxLM+QHgML0Q0+W4SIEiMEWB6Pu6swUda5be/aYFMP8rYdQTTAkmKsyQZAJrpaR/Wh6FTUVBLjywIFb7cL03hC8V/OLrOGXOYSqPRZxN0u2dVmnUqETNZdQce+3nuwRt8p/XxTLPDyxggBHLn4uDm88kBfH9C96eoQK7OwSwuRtFY3UiwbV33WyuebxEAm170dItio2Po1HROI6olN0tbKuSSAH4nHSXppZ59mHcZrFKvX83lVs0HI+rVqgePD9N1+wQ7BMZDD+EBOZIYd405RIF2n6DCbtbpTQZSkCROYhaJhs875rqWcxegi6SCIapoRS6gcfXFQoUATK1np3rPll2OI4brLEkEKBF6CFvACBDAI+aIfBYeVckfVU8OIMu67sPnEFBmmRRHVSHuODyVlkQKR8v6GrUvfXkUDPWIcTjLwDgX83uCi+voVLWtwV3vjQ9gOEfokFl099uTmqLWuYTj4+cR0K5iK0Wv3I94BNun1fobbDjnsAx7nE+0JREBuSd24G/QbT5I+YE5kjoRu4Poz62pGbUmd8HDoPH+fLn6PJSbqxGQ3lAbn4S9O00=
