language: ruby
rvm:
- 2.2
branches:
  only:
  - master
script:
- bundle exec jekyll build
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GH_REF}" HEAD:${TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/themodelvillager/bekonscot.git
  - TARGET_BRANCH: gh-pages
  - secure: fvMNIMRCzECkmpe8eOawztcE6hoqQmggcEsldEdB2f4AZA1cFiSvOYCNZLiycmmCcgvi3X72QFGzrSM7yXW1jw4U7Zdc/r3dyg6TFt3rm7vfpfqYEg08T8bzV368CC9D9HYVdzu7oK5s2VCktxGn6SJyOAuwm0LQTeC/Omc/+hW/znXouxw7o+ech2/Og4meneIm8bjbkzP7DMjeplvkspELEG4RhBWMg3KngZ0ptqbLMVksiEJKu5utcou4vqfMtN4eqmdfN8HAdctxXR/abx1geC0sxOdWjRdA2Pk6Ol3jtafTaRwYWqDpSnYUdapzh3gBSn9xmxQsbF+zM/waHmGBMSqLb1Ju38GzrWn5w+iOxHBB7RL1Xl3/1tKlS52/sfItCshZvx8Pbh9E3Ad+sQ9C9xdBWoRcEAZnOAsbCq66DYitoRlt7pYGXx/XPbTnBXN8dk54ratI4VuMnO3NuKIVn8nZieFiEYjwE/5XZaUe1N2WW1BJDOm2BNXikfrWC2I9VtZki6iaNPTVNK3xjqIGI5rSHcuJ2So+ztoebu7akhHTfpeVhVcNdDpmZV+omPnwBPkm7TuWJ/BGDXWmzM90VsnBLh4FnBS3HWvvVIrBzQ59GYvBpDcem7zeGDqR/Li07/78nveimUtgI7i2YetJJW59koyYkPrl25873vg=
  - secure: rhgjhYD9Z2qfO+hCVmYkbqsnup7EJr1zu7GiBBMMohYwyDQ+K4XIsVEklNfA5mhd10L07xo7ynZmr2awDzDCJJgVeAFQr4s5AX9gd+CwDr/X0M9G3Dyt5pe0jSrk9cQC/+Y1GwvHw2f0awuE6IgTMMwyf1rRL0TeSFuXBry/tIq+5MN4zyqHwX0WwQOl2stp0hzZQEcbH2euOsFPqjbbiPiZMauTpNoowjTnO5iAuU1kKZkPrJCnWirBKdmZYukDNgmyS9xzsvulW4yW8RfykCGCWeCTfuC5Uk+9J4FuDRs6etAKLfxEXvqNHwb5g6AVsQmLvbyfNPsLevY2Y0PZrzVu3LgFR4v/1sWGIC1Uuq87Y7kl3L2UC5XhWKlB0akQcqgpkM1/7AsQnrPUcYJ23O9Q97dz7UupcEOO3PL+7R79F3siCp3k5rtVa0fCo3YQM2SN2dQE+PeQGPHt0gq0Eiz9NU4cVBCKmHlo35P/wm6NUtDTNs4XS06ILlVmUw3PJZaiy05b1n4mh/28gopT18oUWfOd1/DKD7UVRIPxZTaXxc2ChvQ0nkZOVyLSAL2xeLQyfEV905aT7vhNTBz8V9SD97sgfC0+P1IGhg38WTbGuBcikKo99DQLkjrp0zghI8gciy1IDbDkMkBZl8mTv+cYpZ0fKw0gWY4UpGiQq4c=
