defaults:
  -
    values:
      layout: "default"

gallerytag:
    dir: images
    url: /images

# Site settings
title: Bekonscot Model Village
baseurl: "/bekonscot"
url: "http://nickdunn.github.io" # the base hostname & protocol for your site

markdown: kramdown