# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

defaults:
  -
    values:
      layout: "default"

gallerytag:
    dir: images
    url: /images

# Site settings
title: Bekonscot Model Village
baseurl: "/bekonscot"
url: "http://nickdunn.github.io" # the base hostname & protocol for your site

markdown: kramdown