defaults:
  -
    values:
      layout: "default"

title: Bekonscot Model Village
baseurl: "/bekonscot"
url: "http://themodelvillager.github.io"

markdown: kramdown
permalink: pretty

exclude: [vendor]